Added case-sensitivity warning
rocker-org/devcontainer-features pull request #219
Opened 2024-04-30 18:59 UTC by mthomas-ketchbrook

Considering R users who may used to installing R packages via `install.packages(...)` (where package names may be a mix of upper- and lower-case letters) from an R session, I believe it may be useful to document that installing R packages via `apt-packages` requires that the package name be lowercase within `r-cran-<package>`.

2024-04-30 22:45 UTC, eitsupi requested changes
Thank you for your contribution!

However, I think it is too topical to mention r-cran-* here (i.e., I believe that this Feature is used more often for purposes other than R package installation).
How about adding to the following section?

https://github.com/rocker-org/devcontainer-features/blob/95fb05b08dc2a8e94c4c4ef52e8c08de3bea277a/src/r-apt/README.md?plain=1#L65-L82

And, it seems that uppercase letters cannot be used in apt package names in the first place.
https://askubuntu.com/questions/1262528/what-are-usable-characters-are-for-package-names

2024-05-01 00:12 UTC, mthomas-ketchbrook commented
Thank you so much for your kind response!

Embarassingly, I had overlooked the `r-packages` feature when I originally created this PR. The `r-packages` feature seems to be the most "appropriate" place to install R packages.

I'd be happy to add to the section you referenced, and perhaps add an additional comment to simply point out that the `r-packages` feature also exists for the purposes of installing R packages.

Would you prefer that I make these changes to the [NOTES.md](https://github.com/rocker-org/devcontainer-features/blob/main/src/r-apt/NOTES.md) file or the [README.md](https://github.com/rocker-org/devcontainer-features/blob/main/src/r-apt/README.md)?

2024-05-01 13:11 UTC, eitsupi commented
Thanks for checking this out.

Yes, you are correct, the README is automatically generated from the NOTES, so we need to edit the NOTES.

2024-05-02 14:25 UTC, mthomas-ketchbrook commented
I moved the anecdote & example from the `apt-packages` Feature NOTES to the `r-apt` Feature NOTES in [a5d2629](https://github.com/rocker-org/devcontainer-features/pull/219/commits/a5d26296835e976f89399c5a31c409fa7688f889).

Please let me know if this is what you had in mind, or if there are any additional changes I should make.  Thanks!

2024-05-02 14:30 UTC, eitsupi approved these changes
LGTM, thanks!

2024-05-02 14:30 UTC, merged

2024-05-02 14:33 UTC, eitsupi commented
The README has been updated by b24eea2adb7eb39260765f8d0e0cbddc65ac5537.